name: CI

on:
  # Triggers the workflow on push or pull request events for the main and my branch
  push:
    branches:
      - main
      - kirti
      - jai
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Uses the latest version of Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v3 # Checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4 # Sets up Python in the environment
        with:
          python-version: ">=3.10" # Ensures the Python version is at least 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Runs unittests in the tests directory
