name: CI

on:
  # Triggers the workflow on push or pull request events for the main and my branch
  push:
    branches:
      - main
      - kirti
      - jai
      - anji
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Uses the latest version of Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v3 # Checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4 # Sets up Python in the environment
        with:
          python-version: ">=3.8,<3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt
          pip install dvc[gs]

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Runs unittests in the tests directory

      - name: Setup GCP Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Setup DVC
        run: |
          dvc init -f
          dvc remote add -d myremote gs://data_fer2013

      - name: Download data
        run: |
          python pipelines/data_pipeline/dags/src/emotion_data_downloader.py
          python pipelines/data_pipeline/dags/src/song_data_pipeline.py

      - name: Check Data Anomaly
        run: |
          python pipelines/data_pipeline/dags/src/anomaly.py
          
      - name: Pull DVC data
        run: |
          dvc pull -v

      - name: Push DVC data
        run: |
          dvc add dags/data/raw/dataset_fer2013.csv dags/data/raw/song_dataset.csv
          dvc push

      - name: Commit DVC changes
        run: |
          git config --local user.email "anjith16@gmail.com"
          git config --local user.name "anuttan"
          git add dags/data/raw/dataset_fer2013.csv.dvc dags/data/raw/song_dataset.csv.dvc .dvc/config
          git commit -m "Update DVC tracked data [skip ci]" || echo "No changes to commit"
          git push origin main