name: Data Pipeline

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  COMPOSER_ENVIRONMENT: "data-pipeline"
  COMPOSER_LOCATION: "us-east1"
  COMPOSER_IMAGE_VERSION: "composer-2.5.3-airflow-2.5.3"
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  setup-and-run-composer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Setup Cloud Composer Environment
        run: python pipelines/dags/src/setup_composer.py

      - name: Deploy DAG to Cloud Composer
        run: python pipelines/dags/src/deploy_dag.py